sudo: false
# before_install:
# - sudo apt -qq update
# - sudo apt install -y jq
install:
- . ./travis-helper.sh
services:
- docker
# env:
before_script:
- docker run --env-file build.env -d --name pinect -v $PWD:/srv -v /dev:/dev -v /sys:/sys --privileged --cap-add=ALL -w /srv alpine /bin/sleep 36000
script:
- docker exec pinect apk add --update-cache wget jq bash git
- docker exec pinect ./build.sh
# before_deploy:
deploy:
  provider: releases
  api_key:
    secure: OkUr9YOOPPuFfEpFcuXILZbsRBl76pUsfRR4srLWhr7e7m7ynU4tkrLzsQtLrrnqQiOnaiQb9g0Uw9CDQ2qHRITIyRex/v3rLD+/nPdGfsc5EhP+y39LY0tu8saVR/E9d6LjZ/kJqODVskDXcIDu9O8UfkwaE60MJpslp7m2Syp6gCC6EwnSamPyGGp/vguXvcQEaeDvbvERnH20QP5sgC7a5p16jnyXN9k4trBViZ4OUOPsbGecHMPkN7Mxkl3cARI/uQtLV5fZvrwys6iQMgi4iKa1rNFmJjvxxAs7HlXCDcMK16IX+6wb2hzo42sIQY9/vdzWv53CU6PBtNjDReWrInPPVcvjtXh3LKaFkBj1w742zymci5LzYge3uKqisAZ0w74YZUiLaphHI5x/9QJFqdI0aj7hCDxef3174gNhY+q0Qz8CSNE92fGc2BvDY7xAoGJlRRiHRWRQqM5vx2PpiuYneVYvgGLV+sbWvSy2P38+9jwg0K/lSfUg1sxWG1hV9zNtKwUO0kSM1DUxOsVyqlzsAfdXWV7XeRW1gt4lSKCiVJtmGi/xj0wmllnDSKauVG4EU449W3UgfKjn3+6/9VbhTuNS3V4jpD3Ux7O31mm1a0kyb1i/RuFC8s8lhzGiTc1BWg9uvQEs7tsEoSoCLPTOjBIE+H8V00WtM4k=
  # file_glob: true
  file:
    - "haproxy" ## release_n set by build script on successful build
  skip_cleanup: true
  on:
    condition: "$(. ./result.env; echo $NEW_RELEASE) = true"
# after_deploy:
